# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Compiler service CI

on:
  push:
    branches: [ "master", "staging" ]
  pull_request:
    branches: [ "master", "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compiler-service/
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./compiler-service/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: ./compiler-service
    - name: Build
      run: npm run build --if-present
      working-directory: ./compiler-service
    - name: Test
      run: npm test
      working-directory: ./compiler-service
